### ISSUE TITLE
Update reCAPTCHA

### ISSUE THREAD

**Issue by roskakori** [pygraz/old-django-website#11]
If you go to https://pygraz.org/meetups/sessions/submit/ the Captcha field reads: "reCAPTCHA v1 is shutdown".

There's a [reCAPTCHA v2 API](https://developers.google.com/recaptcha/docs/display) that inlines some JavaScript code and then can be [verified](https://developers.google.com/recaptcha/docs/verify) using (among other options) a POST query with a JSON reply.

Original bug report by @meisterluk: https://www.meetup.com/PyGRAZ/discussions/5631445632811008/.

**Comment by meisterluk** [comment]
Who has access to request a new API key? [via](https://developers.google.com/recaptcha/docs/faq#what-happens-to-recaptcha-v1)

**Comment by meisterluk** [comment]
Any updates on this issue?

**Comment by stefan2904** [comment]
It's the topic of the next meetup at 2018-07-03:
https://grical.realraum.at/e/show/1109/

(I took the liberty to [fix the title](https://grical.realraum.at/e/history/1109/).)

**Comment by meisterluk** [comment]
@stefan2904  Thanks, I know. This was discussed at the last meetup.
