### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by roskakori** [pygraz/old-django-website#31]
## Goals

Requires #30.

- [x] Developers can activate a pre-commit hook that performs reasonable static checks in the code.
  - [x] The pre-commit config is based on the one used by the [django_html_xml_validator](https://github.com/itell-solutions/django_html_xml_validator/blob/main/.pre-commit-config.yaml).
- [x] The CI checks towards the pre-commit hooks.

**Comment by roskakori** [comment]
@Dorianux Please test if the hooks work on your machine too. The README should be up to date. 

Quick instructions for you:
```bash
git pull
pip install -r requirements/development.txt
pre-commit install
pre-commit run --all-files  # --> should not produce any errors
```
After that, every time you commit, the pre-commit hooks should run.

**Comment by Dorianux** [comment]
lauft ohne Proleme durch
